---
name: "push"

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Image tag name.'
        required: true
  release:
    types:
      - published

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Build:checkout"
        uses: actions/checkout@v2
      - name: "Set image tag name"
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "IMAGETAG=${{ github.event.inputs.image_tag }}" >> $GITHUB_ENV
          else
            echo "IMAGETAG=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          fi
      - name: "Check image tag name"
        run: |
          echo "IMAGETAG=${{env.IMAGETAG}}"
      - name: "Build:buildx"
        uses: docker/setup-buildx-action@v1
        with:
          version: v0.9.1 # Buildx version

      - name: Build image
        run: |
          docker build -t test -f Dockerfile.controller .
